services:
  - type: web
    name: gaming-verse
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://api.boomchainlab.com
